/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lance_tan
 */
public class addSubjectForm extends javax.swing.JFrame {

        /**
         * Creates new form addSubjectForm
         */
        
        MainMenu myMainMenu;
        
        public addSubjectForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;

        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                txtAddSubject = new javax.swing.JTextField();
                btnAdd = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                setResizable(false);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                lblTitle.setText("Adding Subject");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 180, 80));
                getContentPane().add(txtAddSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });
                getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "subjectForm"); //To switch back to subject form
                myMainMenu.mySubjectForm.refresh(); //Refreshes the subject form
                this.txtAddSubject.setText("");
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                if(txtAddSubject.getText().equals("")) {
                        JOptionPane.showMessageDialog(new JFrame(), "Please do not leave Subject Name field blank", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                        myMainMenu.mySQLMain.addItem("tblSubject", "SubjectName", this.txtAddSubject.getText()); //Adds it onto the database
                        myMainMenu.navigate(this, "subjectForm"); 
                        myMainMenu.mySubjectForm.refresh();
                        this.txtAddSubject.setText("");
                }
        }//GEN-LAST:event_btnAddActionPerformed

        /**
         * @param args the command line arguments
         */
        

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTextField txtAddSubject;
        // End of variables declaration//GEN-END:variables
}
