/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class chooseTopicForm extends javax.swing.JFrame {

        /**
         * Creates new form chooseTopicForm
         */
        
        MainMenu myMainMenu;
        
        public chooseTopicForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                txtTopicName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel1.setText("Choosing Existing Quiz");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

                jLabel2.setText("Step 2: Select Topic");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
                getContentPane().add(txtTopicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));

                jLabel3.setText("Topic Name");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtTopicName.setText(myMainMenu.mySQLMain.previousItem("TopicName")); //Moves between the different topic names in the database
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtTopicName.setText(myMainMenu.mySQLMain.nextItem("TopicName"));
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "chooseSubjectForm"); //Switch back the frame
                myMainMenu.myChooseSubjectForm.refresh(); //Refreshes the choose subject form
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "chooseClassForm"); //Switches to the choose class form
                int ID = myMainMenu.mySQLMain.retrieveID("TopicID", "tblTopic", "TopicName", this.txtTopicName.getText()); //Gets the ID of the chosen class
                myMainMenu.currentTopicID = ID;
                myMainMenu.myChooseClassForm.refresh();
        }//GEN-LAST:event_btnNextActionPerformed

        public void refresh() { //Makes sure that data from the databases are showing
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery(String.format("SELECT * FROM tblTopic WHERE SubjectID=%d", myMainMenu.currentSubjectID));
                        myMainMenu.mySQLMain.rs.next();
                        this.txtTopicName.setText(myMainMenu.mySQLMain.rs.getString("TopicName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtTopicName;
        // End of variables declaration//GEN-END:variables
}
