/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class chooseClassForm extends javax.swing.JFrame {

        /**
         * Creates new form chooseClassForm
         */
        
        MainMenu myMainMenu;
        
        public chooseClassForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtClass = new javax.swing.JTextField();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setText("Step 3: Select Class");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

                jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel2.setText("Choosing Existing Quiz");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

                jLabel3.setText("Class");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
                getContentPane().add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtClass.setText(myMainMenu.mySQLMain.previousItem("ClassName")); //To swtich between classes
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtClass.setText(myMainMenu.mySQLMain.nextItem("ClassName")); //To switch between classes
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "chooseTopicForm"); //To go back to the choose topic form
                myMainMenu.myChooseTopicForm.refresh(); //Refreshes the choose topic form
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "chooseQuizForm"); //Switch frames to the choose quiz form
                int ID = myMainMenu.mySQLMain.retrieveID("classID", "tblClass", "ClassName", this.txtClass.getText()); //Gets the ID of the class that was just chosen
                myMainMenu.currentClassID = ID;
                myMainMenu.myChooseQuizForm.refresh(); //Refreshes the choose quiz form
        }//GEN-LAST:event_btnNextActionPerformed

        public void refresh() { //Refresh method to make sure that the data from the databases show
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery(String.format("SELECT * FROM tblClass WHERE SubjectID=%d", myMainMenu.currentSubjectID));
                        myMainMenu.mySQLMain.rs.next();
                        this.txtClass.setText(myMainMenu.mySQLMain.rs.getString("ClassName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtClass;
        // End of variables declaration//GEN-END:variables
}
