/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class chooseQuizForm extends javax.swing.JFrame {

        /**
         * Creates new form chooseQuizForm
         */
        
        MainMenu myMainMenu;
        
        public chooseQuizForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtQuizName = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtDescription = new javax.swing.JTextArea();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel1.setText("Choosing Existing Quiz");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

                jLabel2.setText("Step 4: Select Quiz");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

                jLabel3.setText("Quiz Name");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
                getContentPane().add(txtQuizName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));

                jLabel4.setText("Description");
                getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

                txtDescription.setColumns(20);
                txtDescription.setRows(5);
                jScrollPane1.setViewportView(txtDescription);

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtQuizName.setText(myMainMenu.mySQLMain.previousItem("Title")); //Sets the quiz name to the title of the different quizzes 
                this.txtDescription.setText(myMainMenu.mySQLMain.previousItem("Description")); //Sets the description to the different descriptions
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtQuizName.setText(myMainMenu.mySQLMain.nextItem("Title"));
                this.txtDescription.setText(myMainMenu.mySQLMain.nextItem("Description"));
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "chooseClassForm"); //Goes back to the choose class form
                myMainMenu.myChooseClassForm.refresh(); //Refreshes the choose class form
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "formatForm"); //Moves to the format form
                int ID = myMainMenu.mySQLMain.retrieveID("quizID", "tblQuiz", "Title", this.txtQuizName.getText()); //Retrieves the ID of the chosen quiz
                myMainMenu.currentQuizID = ID; 
                myMainMenu.quizName = this.txtQuizName.getText();
        }//GEN-LAST:event_btnNextActionPerformed
        
        public void refresh() { //Makes sure that data from the databases are shown
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery(String.format("SELECT * FROM tblQuiz WHERE SubjectID=%d", myMainMenu.currentSubjectID));
                        myMainMenu.mySQLMain.rs.next();
                        this.txtQuizName.setText(myMainMenu.mySQLMain.rs.getString("Title"));
                        this.txtDescription.setText(myMainMenu.mySQLMain.rs.getString("Description"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea txtDescription;
        private javax.swing.JTextField txtQuizName;
        // End of variables declaration//GEN-END:variables
}
