/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class chooseSubjectForm extends javax.swing.JFrame {

        /**
         * Creates new form chooseClassForm
         */
        
        MainMenu myMainMenu;
        
        public chooseSubjectForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                txtSubject = new javax.swing.JTextField();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel1.setText("Choosing Existing Quiz");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

                jLabel2.setText("Step 1: Select Subject");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

                jLabel3.setText("Subject Name");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

                txtSubject.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSubjectActionPerformed(evt);
                        }
                });
                getContentPane().add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "mainMenu"); //Goes back to the main menu
        }//GEN-LAST:event_btnBackActionPerformed

        private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txtSubjectActionPerformed

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtSubject.setText(myMainMenu.mySQLMain.previousItem("SubjectName")); //Moves between the different subjects in the database
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtSubject.setText(myMainMenu.mySQLMain.nextItem("SubjectName"));
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                int ID = myMainMenu.mySQLMain.retrieveID("SubjectID", "tblSubject", "SubjectName", this.txtSubject.getText()); //Gets the ID of the subject that was chosen
                myMainMenu.navigate(this, "chooseTopicForm"); //Switch to the next frame
                myMainMenu.currentSubjectID = ID;
                myMainMenu.myChooseTopicForm.refresh(); //Refreshes the choose topic form
        }//GEN-LAST:event_btnNextActionPerformed

        public void refresh() { //Makes sure that data from the databases are shown
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery("SELECT * FROM tblSubject");
                        myMainMenu.mySQLMain.rs.next();
                        this.txtSubject.setText(myMainMenu.mySQLMain.rs.getString("SubjectName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtSubject;
        // End of variables declaration//GEN-END:variables
}
