/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class classForm extends javax.swing.JFrame {

        /**
         * Creates new form classForm
         */
        
        MainMenu myMainMenu;
        
        public classForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
                
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblStep3 = new javax.swing.JLabel();
                lblClass = new javax.swing.JLabel();
                txtClass = new javax.swing.JTextField();
                btnAdd = new javax.swing.JButton();
                btnRemove = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(0, 0));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

                lblStep3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
                lblStep3.setText("Step 3: Choose Class");
                getContentPane().add(lblStep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

                lblClass.setText("Class");
                getContentPane().add(lblClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
                getContentPane().add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, -1));

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });
                getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

                btnRemove.setText("Remove");
                btnRemove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRemoveActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "quizForm"); //Switches to the quiz form
                int ID = myMainMenu.mySQLMain.retrieveID("classID", "tblClass", "ClassName", this.txtClass.getText()); //Gets the ID of the chosen class
                myMainMenu.currentClassID = ID;
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "topicForm"); //Switches to the topic form
                myMainMenu.myTopicForm.refresh(); //Refreshes the topic form
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "addClassForm"); //Switches to the add class form
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
                // TODO add your handling code here:
                String text = this.txtClass.getText();
                myMainMenu.mySQLMain.removeItem("tblClass", "ClassName", text); //Removes the class from the database
                this.refresh();
        }//GEN-LAST:event_btnRemoveActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtClass.setText(myMainMenu.mySQLMain.nextItem("ClassName")); //Moves between different classes in the database
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtClass.setText(myMainMenu.mySQLMain.previousItem("ClassName"));
        }//GEN-LAST:event_btnLeftActionPerformed

        /**
         * @param args the command line arguments
         */
        
        public void refresh() { //Makes sure that data from the databases show
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery(String.format("SELECT * FROM tblClass WHERE SubjectID=%d", myMainMenu.currentSubjectID));
                        myMainMenu.mySQLMain.rs.next();
                        this.txtClass.setText(myMainMenu.mySQLMain.rs.getString("ClassName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRemove;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel lblClass;
        private javax.swing.JLabel lblStep3;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTextField txtClass;
        // End of variables declaration//GEN-END:variables
}
