/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class finalForm extends javax.swing.JFrame {

        /**
         * Creates new form finalForm
         */
        
        MainMenu myMainMenu;
        
        public finalForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }
        

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                btnReturn = new javax.swing.JButton();
                btnClose = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel1.setText("YOUR QUIZ HAS BEEN EXPORTED.");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

                jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel2.setText("CHECK YOUR DESKTOP TO FIND THE ");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

                jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel3.setText("EXCEL FILE FOR YOUR SELECTED QUIZ TYPE.");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

                btnReturn.setText("Return to Main Menu");
                btnReturn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReturnActionPerformed(evt);
                        }
                });
                getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

                btnClose.setText("Close");
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCloseActionPerformed(evt);
                        }
                });
                getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "mainMenu"); //Switches back to the main menu
        }//GEN-LAST:event_btnReturnActionPerformed

        private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
                // TODO add your handling code here:
                System.exit(0); //Closes the program
        }//GEN-LAST:event_btnCloseActionPerformed

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnReturn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        // End of variables declaration//GEN-END:variables
}
