/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.BufferedReader;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;



/**
 *
 * @author lance_tan
 */
public class importKTAuto extends javax.swing.JFrame {

        /**
         * Creates new form importKTAuto
         */
        
        MainMenu myMainMenu;
        
        public importKTAuto(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblStep = new javax.swing.JLabel();
                btnImport = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                tblKT = new javax.swing.JScrollPane();
                tblKeyTerm = new javax.swing.JTable();
                btnNext = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

                lblStep.setText("Step 4: Importing Key Terms and/or Definitions");
                getContentPane().add(lblStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

                btnImport.setText("Import .txt File");
                btnImport.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnImportActionPerformed(evt);
                        }
                });
                getContentPane().add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

                tblKeyTerm.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Key Terms"
                        }
                ));
                tblKT.setViewportView(tblKeyTerm);

                getContentPane().add(tblKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 230, 130));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });
                getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
                // TODO add your handling code here:
                //Creates a new JFileChoose object
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
                //Opens up a file directory for the user to look for their file
		int returnValue = jfc.showOpenDialog(null);
                //Checks weather the returnValue was chosen
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			File selectedFile = jfc.getSelectedFile();
                        //Stores the path of the file that was chosen  
			String path = selectedFile.getAbsolutePath();
                        //Instantiates a file object with the path of the chosen file
                        File file = new File(path);                        
                        try {
                                //Instantiates a new bufferedReader object, which has the fileReader of the current file
                                BufferedReader br = new BufferedReader(new FileReader(file));
                                //Creates the object for putting the data into the table
                                DefaultTableModel model = (DefaultTableModel)tblKeyTerm.getModel();
                                //Goes through each line in the file and turns it into an Object array
                                Object[] tableLines = br.lines().toArray(); 
                                //Loops through each item in the array
                                for(int i = 0; i < tableLines.length; i++) {
                                    //Converts each line to a string and removes any whitespaces in the start and end
                                    String line = tableLines[i].toString().trim();
                                    //Splits each line when there is a new line in the text file
                                    String[] dataRow = line.split("\n"); 
                                    model.addRow(dataRow); //Adds the data into the table
                                }
                        } catch (Exception e) {
                                System.out.println("Error 1: " + e);
                        }
		}
        }//GEN-LAST:event_btnImportActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "importFormat"); //Switching frames
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "choosingDefinition"); 
                myMainMenu.previousFrame = "importKTAuto";
                addToKeyTermsArray(); 
                myMainMenu.myChoosingDefinition.setUp();
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) tblKeyTerm.getModel(); //Sets the table as a new empty table
                model.setRowCount(0);
        }//GEN-LAST:event_btnClearActionPerformed

        /**
         * @param args the command line arguments
         */
        
        public void addToKeyTermsArray() {
                myMainMenu.keyTerms.clear();
                
                int rows = tblKeyTerm.getRowCount();
                
                for(int i = 0; i < rows; i++) {
                        myMainMenu.keyTerms.add((String) tblKeyTerm.getModel().getValueAt(i, 0));
                }
        }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnImport;
        private javax.swing.JButton btnNext;
        private javax.swing.JLabel lblStep;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JScrollPane tblKT;
        private javax.swing.JTable tblKeyTerm;
        // End of variables declaration//GEN-END:variables
}
