/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;


/**
 *
 * @author lance_tan
 */
public class importKTManual extends javax.swing.JFrame {

        /**
         * Creates new form importKTManual
         */
        
        MainMenu myMainMenu;
        
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        
        public importKTManual(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
                
                this.cbItem.removeAllItems();
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblStep = new javax.swing.JLabel();
                txtKT = new javax.swing.JTextField();
                btnAdd = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                btnRemove = new javax.swing.JButton();
                cbItem = new javax.swing.JComboBox<>();
                btnNext = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setFocusTraversalKeysEnabled(false);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

                lblStep.setText("Step 4: Importing Key Terms and/or Definitions");
                getContentPane().add(lblStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
                getContentPane().add(txtKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, -1));

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });
                getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

                btnRemove.setText("Remove");
                btnRemove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRemoveActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

                cbItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cbItem.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cbItemItemStateChanged(evt);
                        }
                });
                cbItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbItemActionPerformed(evt);
                        }
                });
                getContentPane().add(cbItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });
                getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "importFormat"); //Switching frames
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                this.add(this.txtKT.getText()); //Gets the text that is in the text box
                
                this.txtKT.setText("");
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
                // TODO add your handling code here:
                this.delete(this.cbItem.getSelectedIndex()); //Removes items from the list
        }//GEN-LAST:event_btnRemoveActionPerformed

        private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItemActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_cbItemActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "choosingDefinition");
                myMainMenu.previousFrame = "importKTManual";
                addToKeyTermsArray();
                myMainMenu.myChoosingDefinition.setUp();
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                dm = new DefaultComboBoxModel();
                this.cbItem.setModel(dm);
        }//GEN-LAST:event_btnClearActionPerformed

        private void cbItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemItemStateChanged
                // TODO add your handling code here:
                //this.txtKT.setText(this.cbItem.getSelectedItem().toString());
        }//GEN-LAST:event_cbItemItemStateChanged

        /**
         * @param args the command line arguments
         */
        
        //Add data to JCombo
        public void add(String keyTerm) {
                //Add to dm
                dm.addElement(keyTerm);
                
                //Bind it to combo
                this.cbItem.setModel(dm);
                
                //Select programmatically
                dm.setSelectedItem(keyTerm);
        }
        
        //Delete
        public void delete(int index) {
                dm.removeElementAt(index);
        }
        
        public void addToKeyTermsArray() {
                myMainMenu.keyTerms.clear();
                
                int rows = dm.getSize();
                
                for(int i = 0; i < rows; i++) {
                        myMainMenu.keyTerms.add((String) dm.getElementAt(i));
                }
        }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRemove;
        private javax.swing.JComboBox<String> cbItem;
        private javax.swing.JLabel lblStep;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTextField txtKT;
        // End of variables declaration//GEN-END:variables
}
