/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class importFormat extends javax.swing.JFrame {

        /**
         * Creates new form importFormat
         */
        
        MainMenu myMainMenu;
        String importType;
        
        public importFormat(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
                
                importType = "";
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblStep = new javax.swing.JLabel();
                btnManually = new javax.swing.JButton();
                btnTXTFile = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                lblInstruction = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(400, 300));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

                lblStep.setText("Step 4: Importing Key Terms and/or Definitions");
                getContentPane().add(lblStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

                btnManually.setText("Manually");
                btnManually.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnManuallyActionPerformed(evt);
                        }
                });
                getContentPane().add(btnManually, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

                btnTXTFile.setText(".txt File");
                btnTXTFile.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTXTFileActionPerformed(evt);
                        }
                });
                getContentPane().add(btnTXTFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

                lblInstruction.setText("How will you import your key terms and/or definitions?");
                getContentPane().add(lblInstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "importKTorD"); //Switching between frames
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnManuallyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuallyActionPerformed
                // TODO add your handling code here:
                if(importType.equals("KT")) {
                        myMainMenu.navigate(this, "importKTManual");
                } else {
                        myMainMenu.navigate(this, "importKTandDManual");
                }
        }//GEN-LAST:event_btnManuallyActionPerformed

        private void btnTXTFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTXTFileActionPerformed
                // TODO add your handling code here:
                if(importType.equals("KT")) {
                        myMainMenu.navigate(this, "importKTAuto");
                } else {
                        myMainMenu.navigate(this, "importKTandDAuto");
                }
        }//GEN-LAST:event_btnTXTFileActionPerformed

        /**
         * @param args the command line arguments
         */


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnManually;
        private javax.swing.JButton btnTXTFile;
        private javax.swing.JLabel lblInstruction;
        private javax.swing.JLabel lblStep;
        private javax.swing.JLabel lblTitle;
        // End of variables declaration//GEN-END:variables
}
