/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import javax.swing.JFrame;
import java.util.ArrayList;

/**
 *
 * @author lance_tan
 */
public class MainMenu extends javax.swing.JFrame {
        
        
        //Initiaising forms and global variables
        subjectForm mySubjectForm; 
        addSubjectForm myAddSubjectForm;
        topicForm myTopicForm;
        addTopicForm myAddTopicForm;
        classForm myClassForm;
        addClassForm myAddClassForm;
        importKTorD myImportKTorD;
        importFormat myImportFormat;
        importKTManual myImportKTManual;
        importKTandDManual myImportKTandDManual;
        importKTAuto myImportKTAuto;
        sqlMain mySQLMain;
        formatForm myFormatForm;
        importKTandDAuto myImportKTAndDAuto;
        quizForm myQuizForm;
        choosingDefinition myChoosingDefinition;
        apiMain myAPIMain;
        excelMain myExcelMain;
        finalForm myFinalForm;
        chooseSubjectForm myChooseSubjectForm;
        chooseTopicForm myChooseTopicForm;
        chooseClassForm myChooseClassForm;
        chooseQuizForm myChooseQuizForm;
        
        int currentSubjectID;
        int currentTopicID;
        int currentClassID;
        int currentQuizID;
        ArrayList<String> keyTerms;
        
        String previousFrame;
        String quizName;

        /**
         * Creates new form MainMenu
         */
        public MainMenu() {
                initComponents();
                
                //Creating the forms
                mySubjectForm = new subjectForm(this);
                myAddSubjectForm = new addSubjectForm(this);
                myTopicForm = new topicForm(this);
                myAddTopicForm = new addTopicForm(this);
                myClassForm = new classForm(this);
                myAddClassForm = new addClassForm(this);
                myImportKTorD = new importKTorD(this);
                myImportFormat = new importFormat(this);
                myImportKTManual = new importKTManual(this);
                myImportKTandDManual = new importKTandDManual(this);
                myImportKTAuto = new importKTAuto(this);
                mySQLMain = new sqlMain();
                myFormatForm = new formatForm(this);
                myImportKTAndDAuto = new importKTandDAuto(this);
                myQuizForm = new quizForm(this);
                myChoosingDefinition = new choosingDefinition(this);
                myAPIMain = new apiMain(this);
                myExcelMain = new excelMain(this);
                myFinalForm = new finalForm(this);
                myChooseSubjectForm = new chooseSubjectForm(this);
                myChooseTopicForm = new chooseTopicForm(this);
                myChooseClassForm = new chooseClassForm(this);
                myChooseQuizForm = new chooseQuizForm(this);
                
                currentSubjectID = 0;
                currentTopicID = 0;
                currentClassID = 0;
                currentQuizID = 0;
                keyTerms = new ArrayList<>();
                
                previousFrame = "";
                quizName = "";
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                btnCNQ = new javax.swing.JButton();
                btnCEQ = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                setResizable(false);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
                lblTitle.setText("Quiz Generating Software");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

                btnCNQ.setText("Create New Quiz");
                btnCNQ.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCNQActionPerformed(evt);
                        }
                });
                getContentPane().add(btnCNQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

                btnCEQ.setText("Choose Existing Quiz");
                btnCEQ.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCEQActionPerformed(evt);
                        }
                });
                getContentPane().add(btnCEQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCNQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNQActionPerformed
                // TODO add your handling code here:
                this.navigate(this, "subjectForm"); //To move onto the choosing subject frame for creating new quiz
                this.mySubjectForm.refresh(); //Refreshes the subject page so that the data from databases show
        }//GEN-LAST:event_btnCNQActionPerformed

        private void btnCEQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEQActionPerformed
                // TODO add your handling code here:
                this.navigate(this, "chooseSubjectForm"); //To move onto the choosing subject frame for choosing existing quiz
                this.myChooseSubjectForm.refresh();
        }//GEN-LAST:event_btnCEQActionPerformed

        /**
         * @param current
         * @param next
         */
        
        public void navigate(JFrame current, String next) { //Navigate variable is used by all forms for switching between frames
                current.setVisible(false);
                switch(next) {
                        case "subjectForm":
                                mySubjectForm.setVisible(true);
                                break;
                        case "addSubjectForm":
                                myAddSubjectForm.setVisible(true);
                                break;
                        case "topicForm":
                                myTopicForm.setVisible(true);
                                break;
                        case "addTopicForm":
                                myAddTopicForm.setVisible(true);
                                break;
                        case "classForm":
                                myClassForm.setVisible(true);
                                break;
                        case "importKTorD":
                                myImportKTorD.setVisible(true);
                                break;
                        case "addClassForm":
                                myAddClassForm.setVisible(true);
                                break;
                        case "importFormat":
                                myImportFormat.setVisible(true);
                                break;
                        case "importKTManual":
                                myImportKTManual.setVisible(true);
                                break;
                        case "importKTandDManual":
                                myImportKTandDManual.setVisible(true);
                                break;
                        case "importKTAuto":
                                myImportKTAuto.setVisible(true);
                                break;
                        case "formatForm":
                                myFormatForm.setVisible(true);
                                break;
                        case "importKTandDAuto":
                                myImportKTAndDAuto.setVisible(true);
                                break;
                        case "quizForm":
                                myQuizForm.setVisible(true);
                                break;
                        case "choosingDefinition":
                                myChoosingDefinition.setVisible(true);
                                break;
                        case "finalForm":
                                myFinalForm.setVisible(true);
                                break;
                        case "chooseSubjectForm":
                                myChooseSubjectForm.setVisible(true);
                                break;
                        case "chooseTopicForm":
                                myChooseTopicForm.setVisible(true);
                                break;
                        case "chooseClassForm":
                                myChooseClassForm.setVisible(true);
                                break;
                        case "chooseQuizForm":
                                myChooseQuizForm.setVisible(true);
                                break;
                        default:
                                this.setVisible(true);
                }
        }
        
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch(Exception e) {
                        e.toString();
                }
                /*catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } */
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        new MainMenu().setVisible(true);
                });
        }
     

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCEQ;
        private javax.swing.JButton btnCNQ;
        private javax.swing.JLabel lblTitle;
        // End of variables declaration//GEN-END:variables
}
