package forms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lance_tan
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class quizForm extends javax.swing.JFrame {

        /**
         * Creates new form quizForm
         */
        
        MainMenu myMainMenu;
        
        public quizForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblQuizName = new javax.swing.JLabel();
                txtQuizName = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtDescription = new javax.swing.JTextArea();
                btnNext = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

                lblQuizName.setText("Quiz Name*:");
                getContentPane().add(lblQuizName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
                getContentPane().add(txtQuizName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, -1));

                jLabel1.setText("Description:");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

                txtDescription.setColumns(20);
                txtDescription.setRows(5);
                jScrollPane1.setViewportView(txtDescription);

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 100));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "classForm"); //Switching between frame
                this.txtQuizName.setText("");
                this.txtDescription.setText("");
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                if(txtQuizName.getText().equals("")) { //Error message
                        JOptionPane.showMessageDialog(new JFrame(), "Please do not leave Quiz Name field blank", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                        myMainMenu.navigate(this, "importKTorD"); //Switch frames
                        
                        if(txtDescription.getText().equals("")) { //Adds item to the database depending on whether description is empty or not
                                myMainMenu.mySQLMain.addItem("tblQuiz", "Title", "DateCreated", "SubjectID", txtQuizName.getText(), myMainMenu.currentSubjectID);
                        } else {
                                myMainMenu.mySQLMain.addItem("tblQuiz", "Title", "Description", "DateCreated", "SubjectID", txtQuizName.getText(), txtDescription.getText(), myMainMenu.currentSubjectID);
                        }
                        
                        myMainMenu.currentQuizID = myMainMenu.mySQLMain.retrieveID("QuizID", "tblQuiz", "Title", this.txtQuizName.getText());
                        myMainMenu.quizName = this.txtQuizName.getText();
                }
                this.txtQuizName.setText("");
                this.txtDescription.setText("");
        }//GEN-LAST:event_btnNextActionPerformed

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnNext;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblQuizName;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTextArea txtDescription;
        private javax.swing.JTextField txtQuizName;
        // End of variables declaration//GEN-END:variables
}
