/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import java.sql.*;

/**
 *
 * @author lance_tan
 */
public class subjectForm extends javax.swing.JFrame {

        /**
         * Creates new form subjectForm
         */
        
        MainMenu myMainMenu;
        
        public subjectForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;  
        }
        
        

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblStep1 = new javax.swing.JLabel();
                lblTitle = new javax.swing.JLabel();
                lblSubjectName = new javax.swing.JLabel();
                txtSubjectName = new javax.swing.JTextField();
                btnRight = new javax.swing.JButton();
                btnLeft = new javax.swing.JButton();
                btnAdd = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                btnRemove = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(400, 300));
                setResizable(false);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblStep1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
                lblStep1.setText("Step 1:  Choose Subject");
                getContentPane().add(lblStep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, -1));

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

                lblSubjectName.setText("Subject Name");
                getContentPane().add(lblSubjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
                getContentPane().add(txtSubjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 50, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, -1));

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });
                getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

                btnRemove.setText("Remove");
                btnRemove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRemoveActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                this.txtSubjectName.setText(myMainMenu.mySQLMain.nextItem("SubjectName")); //Used for switching between data in the databases
        }//GEN-LAST:event_btnRightActionPerformed

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                this.txtSubjectName.setText(myMainMenu.mySQLMain.previousItem("SubjectName"));
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "addSubjectForm"); //Switching frames
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "MainMenu");
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                int ID = myMainMenu.mySQLMain.retrieveID("SubjectID", "tblSubject", "SubjectName", this.txtSubjectName.getText()); //Getting the ID of the chosen subject
                myMainMenu.navigate(this, "topicForm");
                myMainMenu.currentSubjectID = ID;
                myMainMenu.myTopicForm.refresh(); //Refreshes the topic form
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
                // TODO add your handling code here:
                String text = this.txtSubjectName.getText(); //Gets the text of the chosen item
                myMainMenu.mySQLMain.removeItem("tblSubject", "SubjectName", text); //Removes it from the database
                this.refresh();
                
        }//GEN-LAST:event_btnRemoveActionPerformed

        
        public void refresh() { //Makes sure that data from the databases are showing
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery("SELECT * FROM tblSubject");
                        myMainMenu.mySQLMain.rs.next();
                        this.txtSubjectName.setText(myMainMenu.mySQLMain.rs.getString("SubjectName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }
        
        /**
         * @param args the command line arguments
         */
        


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRemove;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel lblStep1;
        private javax.swing.JLabel lblSubjectName;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTextField txtSubjectName;
        // End of variables declaration//GEN-END:variables
}
