/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author lance_tan
 */
public class topicForm extends javax.swing.JFrame {

        /**
         * Creates new form topicForm
         */
        
        MainMenu myMainMenu;
        
        public topicForm(MainMenu someMain) {
                initComponents();
                
                myMainMenu = someMain;
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
         * The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblTitle = new javax.swing.JLabel();
                lblStep2 = new javax.swing.JLabel();
                lblTopicName = new javax.swing.JLabel();
                txtTopicName = new javax.swing.JTextField();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                btnAdd = new javax.swing.JButton();
                btnRemove = new javax.swing.JButton();
                btnLeft = new javax.swing.JButton();
                btnRight = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(0, 0));
                setMinimumSize(new java.awt.Dimension(400, 300));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                lblTitle.setText("Creating New Quiz");
                getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

                lblStep2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
                lblStep2.setText("Step 2: Choose Topic");
                getContentPane().add(lblStep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

                lblTopicName.setText("Topic Name");
                getContentPane().add(lblTopicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
                getContentPane().add(txtTopicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 150, -1));

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });
                getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });
                getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

                btnRemove.setText("Remove");
                btnRemove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRemoveActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

                btnLeft.setText("<");
                btnLeft.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLeftActionPerformed(evt);
                        }
                });
                getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

                btnRight.setText(">");
                btnRight.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRightActionPerformed(evt);
                        }
                });
                getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        
        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "classForm"); //Switching between frames
                int ID = myMainMenu.mySQLMain.retrieveID("TopicID", "tblTopic", "TopicName", this.txtTopicName.getText()); //Gets the ID of the chosen topic
                myMainMenu.currentTopicID = ID;
                myMainMenu.myClassForm.refresh(); //Refreshes the class form
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "subjectForm"); //Switch between frames
                myMainMenu.mySubjectForm.refresh(); //Refrehes the subject form
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                myMainMenu.navigate(this, "addTopicForm"); //Switch between frames
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
                // TODO add your handling code here:
                String text = this.txtTopicName.getText(); //Gets the name of the chosen topic name
                myMainMenu.mySQLMain.removeItem("tblTopic", "TopicName", text); //Removes that from the database
                this.refresh();
        }//GEN-LAST:event_btnRemoveActionPerformed

        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
                // TODO add your handling code here:
                this.txtTopicName.setText(myMainMenu.mySQLMain.previousItem("TopicName")); //Switching between data from the database
        }//GEN-LAST:event_btnLeftActionPerformed

        private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
                // TODO add your handling code here:
                this.txtTopicName.setText(myMainMenu.mySQLMain.nextItem("TopicName"));
        }//GEN-LAST:event_btnRightActionPerformed

        /**
         * @param args the command line arguments
         */
        
        public void refresh() { //Makes sure that data from the databases are showing
                try {
                        myMainMenu.mySQLMain.rs = myMainMenu.mySQLMain.stmt.executeQuery(String.format("SELECT * FROM tblTopic WHERE SubjectID=%d", myMainMenu.currentSubjectID));
                        myMainMenu.mySQLMain.rs.next();
                        this.txtTopicName.setText(myMainMenu.mySQLMain.rs.getString("TopicName"));
                } catch(Exception e) {
                        System.out.println("Error 1: " + e.toString());
                }
        }
        
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnLeft;
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnRemove;
        private javax.swing.JButton btnRight;
        private javax.swing.JLabel lblStep2;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JLabel lblTopicName;
        private javax.swing.JTextField txtTopicName;
        // End of variables declaration//GEN-END:variables
}
